### ISSUE TITLE
 Unhandled 'error' event spawn unoconv ENOENT

### ISSUE THREAD

**Issue by Anil-bohorya** [alphakevin/unoconv-server#1]
unoconv-server username$ ./unoconv-server start
# starting unoconv listener...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn unoconv ENOENT
    at exports._errnoException (util.js:1024:11)

Getting this error while starting server in OSX yosemite

**Comment by alphakevin** [comment]
@Anil-bohorya, please try install unoconv via brew and libreoffice 3.6.5, there is still some issue in MAC OS, see here: https://github.com/dagwieers/unoconv/issues/391

**Comment by alphakevin** [comment]
This issue possibly because `unoconv` is not installed properly;

if you do not need development for `unoconv-server`, you can check out the ready-for-use docker version:

https://github.com/alphakevin/unoconv-server#playing-with-docker
